services:
  transaction:
    image: node:latest
    container_name: transaction
    volumes:
    - ./backend:/app
    ports:
    - "3000:3000"
    command: sh -c "cd /app && npm install && npm run start:dev"
  
  web:
    image: node:latest
    container_name: web
    volumes:
    - ./frontend:/app
    ports:
    - "5000:3000"
    command: sh -c "cd /app && npm install && npm run dev"
  
  blockchain:
    image: node:latest
    container_name: blockchain
    volumes:
    - ./blockchain:/app
    ports:
    - "8545:8545"
    command: sh -c "sh /app/deploySmartContracts/autorun.sh & cd /app && npm install && npx hardhat node"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes: 
    - ./nginx:/app
    ports:
    - "80:80"
    command: sh -c "cp /app/nginx.conf /etc/nginx/nginx.conf && nginx -g 'daemon off;'"

  db:
    image: mariadb:latest
    container_name: db
    volumes:
    - ./db:/var/lib/mysql
    ports:
    - "3306:3306"
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: abc123.

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
    - "8000:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: abc123.
      PMA_PORT: 3306

  redis:
    image: redis:alpine
    container_name: redis
    command: sh -c "redis-server --appendonly yes --requirepass redispass" 

  rabbitmq:
    image: rabbitmq:alpine
    container_name: rabbitmq
